Sprint 7
ClevertecFrontendLab/RC-3222 pull request #6
Opened 2023-03-26 05:09 UTC by RC-3222

2023-03-26 05:22 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679808129/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)

2023-03-26 05:44 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679809456/9-app%20-burger-menu-close-768px.png)

2023-03-26 06:52 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 82%.
Общее количество тестов: 84.
Количество непройденных тестов: 3.

2023-03-26 07:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679814315/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)

2023-03-26 09:29 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679822997/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)

2023-03-26 12:53 UTC, Gaurrus requested changes

2023-03-26 12:53 UTC, Gaurrus commented on src/app.tsx
> +// import { ErrorBoundary } from './utils/error-boundary';
комментик

2023-03-26 12:53 UTC, Gaurrus commented on src/components/calendar/calendar.tsx
> +}, [monthIndex, currentYear]) */
комментик

2023-03-26 12:53 UTC, Gaurrus commented on package.json
![image](https://user-images.githubusercontent.com/85307211/227775142-5d0ae2b7-684d-4ba9-9321-f9cc03dd1386.png)
почему-то  на фулскрин 3 карточки сетка - должно быть 4

2023-03-26 12:53 UTC, Gaurrus commented on src/api/index.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
![image](https://user-images.githubusercontent.com/85307211/227775297-16f19c4d-a060-471e-93c7-050f8891b503.png)
не прокидывается рейтинг и комментарий при изменении комментария

2023-03-26 12:53 UTC, Gaurrus commented on src/api/index.ts
> +import Cookies from 'js-cookie';
![image](https://user-images.githubusercontent.com/85307211/227775367-9d12c667-00b5-4922-aea1-17f33c3a9fb4.png)
 нет пагинации - на 768 ее нужно сдвинуть ниже соглсно дизайну 
![image](https://user-images.githubusercontent.com/85307211/227775406-514edf45-9715-42f5-a39a-c948945c9b18.png)
320 - тоже

2023-03-26 12:53 UTC, Gaurrus commented on src/api/index.ts
> +  users = '/api/users',
![image](https://user-images.githubusercontent.com/85307211/227775661-0846e7e6-1459-45a7-8e0a-c2a734a31bc5.png)
если в мобайле прейти на страницу профиля и открыть категории то там пусто 
![image](https://user-images.githubusercontent.com/85307211/227775716-a87c6bb9-84fa-45bd-8965-764d1508d58f.png)

2023-03-26 12:53 UTC, Gaurrus commented on src/components/common/status-info/status-info.module.scss
> +  max-width: 600px;
это не то же  что `width: 600px ` ?

2023-03-26 12:53 UTC, Gaurrus commented on src/components/forms/styles.module.scss
> +  min-width: 528px;
опять

2023-03-26 12:53 UTC, Gaurrus commented on src/components/forms/styles.module.scss
> +  margin: -48px -56px 32px -56px;
отрицательные margin - очень странно - а ниже положительный  padding - тут явно что то не так

2023-03-26 12:53 UTC, Gaurrus commented on src/components/review-list/review-list.tsx
> +          // isDisabled={!!isUserLeftComments()}
коммент

2023-03-26 12:53 UTC, Gaurrus commented on src/store/sagas/review.ts
> +        message: 'Спасибо, что нашли время изменить оценку!',
было бы красивы если вынес в константы все тексты

2023-03-26 20:31 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 41%.
Общее количество тестов: 47.
Количество непройденных тестов: 6.

2023-03-26 22:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 75.
Количество непройденных тестов: 1.

2023-03-26 22:08 UTC, RC-3222 commented
было бы смешно, если бы не было так грустно..
![image](https://user-images.githubusercontent.com/99599598/227807629-99d47e04-cdf0-46cf-8516-03528c3eb7ed.png)

2023-03-27 00:14 UTC, ValadzkoAliaksei commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
![image](https://user-images.githubusercontent.com/61273546/227813416-e95870e3-678f-43f7-940b-a58bbeadde27.png)
при переключении вида, что-то явно сломалось

2023-03-27 00:14 UTC, ValadzkoAliaksei commented on package.json
> +    "@types/js-cookie": "^3.0.3",
![image](https://user-images.githubusercontent.com/61273546/227813579-64b6fd43-46a3-4ef5-9734-b20311ddde57.png)
Книга забронирована, но если нажать на кнопку то открывается модалка, как будто новая бронь

2023-03-27 00:14 UTC, ValadzkoAliaksei commented on package.json
> +    "@types/react-text-mask": "^5.4.11",
![image](https://user-images.githubusercontent.com/61273546/227813630-dce40ee4-3e71-43df-a8c1-cc603ad2ec24.png)
При бронировании убираем часовой пояс, иначе она криво бронируется потом, на 3 часа раньше

2023-03-27 00:14 UTC, ValadzkoAliaksei commented on package.json
> +    "js-cookie": "^3.0.1",
![image](https://user-images.githubusercontent.com/61273546/227813681-8b653742-f51f-4448-9370-460389a8ff93.png)
если нет аватарки, то котик

2023-03-27 00:14 UTC, ValadzkoAliaksei commented on package.json
> +    "react-text-mask": "^5.5.0",
![image](https://user-images.githubusercontent.com/61273546/227813711-3a0cd34b-a173-40ec-9c5e-851afebb6b4f.png)
Изменение оценки не подтягивается

2023-03-27 00:14 UTC, ValadzkoAliaksei commented on package.json
> +    "react-text-mask": "^5.5.0",
ни в профиле ни в книге по id

2023-03-27 01:37 UTC, RC-3222 commented on package.json
> +    "react-text-mask": "^5.5.0",
Надеюсь, вы это про текст в кнопке (как-то забыл про это), потому что иначе не совсем понимаю, что тут не работало

2023-03-27 01:52 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 82%.
Общее количество тестов: 84.
Количество непройденных тестов: 3.

2023-03-27 03:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 84%.
Общее количество тестов: 84.
Количество непройденных тестов: 1.

2023-03-27 03:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 84%.
Общее количество тестов: 84.
Количество непройденных тестов: 1.

2023-03-27 07:24 UTC, Gaurrus commented on package.json
> +    "react-text-mask": "^5.5.0",
мы здесь про то, что, если юзер оставлял комментарий к книге, то 1. Да кнопка должна быть другая. 2. При  нажатии должен прокидываться рейтинг и тот текст который он оставлял, при открытии этой модалки по этой измененной кнопке.
Пока не устранено.

2023-03-27 09:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 82%.
Общее количество тестов: 84.
Количество непройденных тестов: 3.

2023-03-27 11:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 71%.
Общее количество тестов: 73.
Количество непройденных тестов: 3.

2023-03-27 12:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 63%.
Общее количество тестов: 66.
Количество непройденных тестов: 4.

2023-03-27 12:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RC-3222/1679919400/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)

2023-03-27 16:48 UTC, ValadzkoAliaksei approved these changes

2023-03-27 19:55 UTC, RC-3222 commented
Если кто из менторов ещё сюда заглянет, то напоследок хотел бы ещё поблагодарить их за проделанную работу (уж знаете, проверки заданий посреди ночи и более-менее подробные разъяснения это немного не то, чего я ждал от треннинга на выбывание с начальным кол-вом участников 1000+)

2023-03-27 19:55 UTC, merged